# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
          DISPLAY: ':99'
    services:
      mysql:
        image: mysql:5.7
        env:
          DB_DATABASE: deustovideoclub
          DB_USER: 'spq'
          DB_PASSWORD: 'spq'
          DB_HOST: 'localhost'
        ports:
          - 3306:3306
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up MySQL
      run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE SCHEMA deustovideoclub;" -uroot -proot
          mysql -e "CREATE USER 'spq'@'localhost' IDENTIFIED BY 'spq';" -uroot -proot
          mysql -e "GRANT ALL ON deustovideoclub.* TO 'spq'@'localhost';" -uroot -proot
          mysql -e "SHOW DATABASES;" -uroot -proot
    - name: Crear la pantalla virtual
      run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: |
          cd ./deusto-videoclub
          mvn --batch-mode --update-snapshots compile 
          mvn --batch-mode --update-snapshots datanucleus:enhance
          mvn --batch-mode --update-snapshots datanucleus:schema-create
          mvn --batch-mode --update-snapshots exec:java -Pdatos
    - name: Test Unitarios
      run: |
          cd ./deusto-videoclub
          mvn --batch-mode --update-snapshots test
      
